[package]
name = "keycloak-types"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
regress = "0.10.4"
schemars = "1.0.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
