[package]
name = "keycloak-types2"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = []
k8s-schema = []

[dependencies]
schemars = "1.0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
